services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: your_db_host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: your_db_name
      - key: DB_USERNAME
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password

